name: realdebrid_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/adbonnin/realdebrid_api

environment:
  sdk: ^3.0.0

dependencies:
  http: '>=0.13.0'
  path: ^1.8.0

dev_dependencies:
  lints: any
  test: any
